import { spawnSync } from 'node:child_process';
import { mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { isEncryptedNote } from '../../../../shared/encrypted';
import {
	decryptNote,
	encryptNote,
	generateKey,
	pgpError,
	prepareKey,
	readKey,
	unlockKey,
	type PrivateKey,
	type PublicKey
} from './pgp';

let armored: string;
let pub: PublicKey;
let priv: PrivateKey;

beforeAll(async () => {
	armored = await generateKey('Test', 'correct horse');
	pub = (await readKey(armored)).publicKey;
	priv = await unlockKey(armored, 'correct horse');
});

describe('keys', () => {
	it('generates a passphrase-protected key with an identity', async () => {
		const { info } = await readKey(armored);
		expect(info.userId).toBe('Test');
		expect(info.fingerprint).toMatch(/^[0-9a-f]{40}$/);
		await expect(unlockKey(armored, 'wrong')).rejects.toThrow();
		await unlockKey(armored, 'wrong').catch((e) => expect(pgpError(e)).toBe('Wrong passphrase.'));
	});

	it('imports a key: checks the passphrase, protects an unprotected one', async () => {
		expect(await prepareKey(armored, 'correct horse')).toContain('PRIVATE KEY BLOCK');
		await expect(prepareKey(armored, 'nope')).rejects.toThrow();
		await expect(prepareKey(pub.armor(), 'x')).rejects.toThrow();
		await prepareKey('garbage', 'x').catch((e) => expect(pgpError(e)).toMatch(/armored PGP key/));

		const bare = await generateKey('Bare', '').catch(() => null);
		if (bare) {
			const stored = await prepareKey(bare, 'new pass');
			await expect(unlockKey(stored, 'new pass')).resolves.toBeTruthy();
		}
	});
});

describe('notes', () => {
	it('round-trips the text byte for byte, metadata lines in the clear', async () => {
		const plain = '<!-- dir: rtl -->\n<!-- pinned: true -->\n# سر\r\n\nbody #tag\n';
		const file = await encryptNote(plain, pub);
		expect(
			file.startsWith('<!-- dir: rtl -->\n<!-- pinned: true -->\n-----BEGIN PGP MESSAGE-----')
		).toBe(true);
		expect(file).not.toContain('body');
		expect(isEncryptedNote(file)).toBe(true);
		expect(await decryptNote(file, priv)).toBe(plain);
	});

	it('produces new ciphertext each time and passes plain text through', async () => {
		expect(await encryptNote('x', pub)).not.toBe(await encryptNote('x', pub));
		expect(await decryptNote('# plain', priv)).toBe('# plain');
	});

	it('names the cause when a note was encrypted with another key', async () => {
		const other = await generateKey('Other', 'p');
		const file = await encryptNote('secret', (await readKey(other)).publicKey);
		await decryptNote(file, priv).catch((e) =>
			expect(pgpError(e)).toBe('This note was encrypted with a different key.')
		);
		await expect(decryptNote(file, priv)).rejects.toThrow();
	});
});

// Interop: files open with plain `gpg`, and keys made by gpg work here.
const hasGpg = spawnSync('gpg', ['--version']).status === 0;

describe.skipIf(!hasGpg)('gpg interop', () => {
	let home: string;
	const gpg = (args: string[], input?: string) =>
		spawnSync(
			'gpg',
			['--homedir', home, '--batch', '--pinentry-mode', 'loopback', '--passphrase', 'pw', ...args],
			{ input, encoding: 'utf8' }
		);

	beforeAll(async () => {
		home = await mkdtemp(path.join(tmpdir(), 'fr5a-gpg-'));
	});
	afterAll(async () => {
		spawnSync('gpgconf', ['--homedir', home, '--kill', 'gpg-agent']);
		await rm(home, { recursive: true, force: true });
	});

	it('gpg decrypts a note encrypted here', async () => {
		const key = await generateKey('Interop', 'pw');
		expect(gpg(['--import'], key).status).toBe(0);
		const file = path.join(home, 'note.md');
		await writeFile(
			file,
			await encryptNote('<!-- pinned: true -->\n# Secret\nbody\n', (await readKey(key)).publicKey)
		);
		const out = gpg(['--decrypt', file]);
		expect(out.status).toBe(0);
		expect(out.stdout).toBe('# Secret\nbody\n');
	});

	it('a key generated by gpg encrypts and decrypts here', async () => {
		expect(
			gpg(['--quick-gen-key', 'Made By Gpg', 'future-default', 'default', 'never']).status
		).toBe(0);
		const exported = gpg(['--armor', '--export-secret-keys', 'Made By Gpg']).stdout;
		const stored = await prepareKey(exported, 'pw');
		const file = await encryptNote('hi', (await readKey(stored)).publicKey);
		expect(await decryptNote(file, await unlockKey(stored, 'pw'))).toBe('hi');
	});
});
